### PR TITLE
fix(tools): Add dummy classes to dotnet gen models to avoid compilation errors

### PR DESCRIPTION
**Pull request by ragi-dayananda**
# Description
The 'concerto.scalar.uuid' namespace is automatically added to the .NET models if the CTO file has a property of type UUID. However, since we treat UUID in CTO as 'System.Guid' in .NET, there is no need to add an import namespace to the generated .NET file.

Adding this namespace resulting in build failures in .NET, so update csharp codegen to ignore adding this namespace to .net models. So excluding the concerto scalar namespace in dotnet generated models.

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `main` from `fork:branchname`

### CODE REVIEW

**Review by mttrbrts — COMMENTED** [review]
It would be more robust to specifically filter out the UUID declaration. There may be other Scalars that get added to the concerto.scalar namespace in the future that we do want to generate code for?

**Comment by ragi-dayananda** [comment]
> It would be more robust to specifically filter out the UUID declaration. There may be other Scalars that get added to the concerto.scalar namespace in the future that we do want to generate code for?

Not really. Scalars are generally translated to either dotnet primitive type or System.Guid (in this case). So we would never require import concerto scalar namespace

**Comment by dselman** [comment]
Would this not import any non concerto.* scalars - leading to a similar compilation error? Scalars are primitive types so should never need an import - unless .NET supports them natively...?

**Comment by ragi-dayananda** [comment]
> Would this not import any non concerto.* scalars - leading to a similar compilation error? Scalars are primitive types so should never need an import - unless .NET supports them natively...?

Yes, scalars are primitive and doesn't need an import.

**Comment by ragi-dayananda** [comment]
> Would this not import any non concerto.* scalars - leading to a similar compilation error? Scalars are primitive types so should never need an import - unless .NET supports them natively...?

For the question specific to scalars from non-Concerto namespaces, we may get a compilation error if that namespace contains only scalar declarations. If the namespace has some concepts in it, then there won't be any compilation errors.

**Review by mttrbrts — APPROVED** [review]

**Pull request merged**
